---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
  - name: portmap
    port: 111
    protocol: UDP
  - name: nfs
    port: 2049
    protocol: TCP
  - name: mountd
    port: 20048
  selector:
    app: nfs-server
